name = "TableView"
uuid = "40c74d1a-b44c-5b06-a7c1-6cbea58ea978"
version = "0.7.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSExpr = "97c1335a-c9c5-57fe-bc5d-ec35cebe8660"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"

[compat]
JSExpr = "0.4, 0.5, 1"
JSON = "0.18, 0.19, 0.20, 0.21"
Observables = "0.2, 0.3, 0.4"
Tables = "1"
WebIO = "0.8"
julia = "0.7, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
